security:
  oauth2:
    resource:
      jwk:
        key-set-uri: https://ssotest.login.system.dev.east.paas.geointservices.io/token_keys
    client:
      accessTokenUri: https://ssotest.login.system.dev.east.paas.geointservices.io/oauth/token
      userAuthorizationUri: https://ssotest.login.system.dev.east.paas.geointservices.io/oauth/authorize
      clientId: 29af427c-80f2-4ce2-9feb-22a35ccc2dae
      clientSecret: c46fd8b5-8d08-49b2-84b7-323f72f52895
ssoServiceUrl: https://ssotest.login.system.dev.east.paas.geointservices.io